sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache
    - $HOME/.wp-cli/cache
    - $HOME/.wp-cli/packages/cache

language:
  - php
  - node_js

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

env:
  global:
    - WP_THEME=turnkey-storefront

before_install:
  - phpenv config-rm xdebug.ini

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=6.5.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - composer global require wp-coding-standards/wpcs
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

before_script:
  - curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar
  - npm install && npm run build

script:
  - phpcs --standard=.dev/phpcs.ruleset.xml $(find . -name '*.php')
  - npm run lint
  - echo "Finished check."

before_deploy:
  - mkdir -p /tmp/$WP_THEME
  - rsync -av --exclude-from $TRAVIS_BUILD_DIR/.distignore --delete $TRAVIS_BUILD_DIR/ /tmp/$WP_THEME/
  - cd /tmp
  - zip -rT $TRAVIS_BUILD_DIR/$WP_THEME.zip $WP_THEME/
  - sha256sum -b $TRAVIS_BUILD_DIR/$WP_THEME.zip | awk '{print $1}' | tee $TRAVIS_BUILD_DIR/$WP_THEME.zip.sha256

deploy:
  provider: releases
  api_key:
    secure: LpodoQTGH89qZ/OcATRzrYkkapG41EfMfp2J3Wub+6bL+ZJy8EGBY/ixsi/sFngeklKy6h3+ngTfrsEYsYyPit606U1QmlCCpE4icSFjHNwhw4ORdAQ8vOeh42qJ7SZ6sP8rtAa8wQitz/2q2eq5ioxH+ehkVDXknsUo/4tvQwDxpIO+zyBTJcCKsS0AZW64pQvhnVygbF9b6r8EoZgt9d1uZELaWVLnqxRyS8FM1S2sFNhbzd+dzZjJTXmzIhb0Oakeoebory4iyyWe+gWGyUGVmU1Q5tVyEPLflskdarEQKjygCc5r0Brb2Z5Dqxvb8RXv3BDqKkkOxMtJ0Igoe7JE8yhOLjVXuOa4aK9+TzQhs7YDwrs+lt9eR9w0vcIK0nvHGvzAKtdhiQQaozboENt+ExuKTxQbcy3yqrLT8J1b1+8GthGuryTnc9wecuc7Namh6He4IwTryN/z6vSmrYDnMRTM1bWH5gSrcHCMes4LoX2nSfl+P0RXrPJqcarUpr5EdpYl3156vmbVoHYh23R8VLf0cMPSVAEmLJ5D8LHJ7iXQhsEEfHjZ/tfdXpAHojTnEcHWZYmqcNO4wan49VinEl8R0ukSeoQyp8EX7Bic1tp4MpKjOtJkVLv+E+MORE6JcFTqD2HxBJh/toX8p68DLaicmLC+bJLNmYJeV6M=
  file:
    - "$TRAVIS_BUILD_DIR/$WP_THEME.zip"
    - "$TRAVIS_BUILD_DIR/$WP_THEME.zip.sha256"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: Resellers/wp-turnkey-theme
