sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache
    - $HOME/.wp-cli/cache
    - $HOME/.wp-cli/packages/cache

language:
  - php
  - node_js

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

env:
  global:
    - WP_THEME=turnkey

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar

script:
  - echo "Deploy only"

before_deploy:
  - mkdir -p /tmp/$WP_THEME
  - rsync -av --exclude-from $TRAVIS_BUILD_DIR/.distignore --delete $TRAVIS_BUILD_DIR/ /tmp/$WP_THEME/
  - cd /tmp
  - zip -rT $TRAVIS_BUILD_DIR/$WP_THEME.zip $WP_THEME/
  - sha256sum -b $TRAVIS_BUILD_DIR/$WP_THEME.zip | awk '{print $1}' | tee $TRAVIS_BUILD_DIR/$WP_THEME.zip.sha256

deploy:
  provider: releases
  api_key:
    secure: RCpOMkX8FCBms+i/Bfbg5ELktq7vSErCgAexZMP7X7YSvGnUuBdNnlT8wrjZDZJ9roDHFuqwjoAJWBL6A2j1QomGhNBPsFvfrsvxKrLsArSsx2GctkzSXqre9+vX7garY3v93HCXOYJkPEOY9fpTvkDPwFj3qEaSxnDOVSzepSoVhmlndJ1Vm2Hzr8G1fJdC+cBtgxpikUXRXJ6AW/Spr2V3dvUaWcayar2hwiKXwfOWCm8npqPTgvlCQuUR3ggRL68ZC/+f4mJteIJXYKyarRb77fosnYptpBFy8mYeyi4WchX4Zyhh1Bg4nRe3eIye1oZKcCZPcjsccBMPG505Ox3e43E67TvMIXVStCsS5+EziuUmaAtUoXY1zAHooZd+5mEouGHKId3o0yjHuZaFYH1ubpcnvMNluiOyWCsr+ZzQOgpyV6NJV5T/rwtncjl52IpgjdwLgeq1HQkcv+eKMJmUK9nehUFtCVAyH5AmqWhIYmYuaH1SIFMxgCWshm7KClr7drKQ0EgKkTklzGGT/lFc36TYP3c103FZd9JF4Px6gcEXyA5yXC4Kpb7RFhWg4JMijia1viiCrX/qUXBpTI0NtkqGqHcVUjoqkYVXdCPa6Mu14L+N6A6RnXrRhzDaplgiFkMyj4dkATKuyiEF1X58jEkBw5ZZG+Q6ACPbo10=
  file:
    - "$TRAVIS_BUILD_DIR/$WP_THEME.zip"
    - "$TRAVIS_BUILD_DIR/$WP_THEME.zip.sha256"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: resellers/wp-turnkey-theme
